// Generated by CoffeeScript 1.12.5
var Quickform;

Quickform = (function() {
  function Quickform(prefix, element, percentage) {
    var addAccessors, addItem, addRow, container, getters, pfx, setters;
    if (percentage == null) {
      percentage = 60;
    }
    container = $('#' + element);
    this.prefix = function() {
      return prefix;
    };
    this.element = function() {
      return element;
    };
    getters = {};
    setters = {};
    addAccessors = function(id, set, get) {
      getters[pfx(id)] = set;
      return setters[pfx(id)] = get;
    };
    addItem = function(percent, value) {
      var section;
      section = $('<section/>');
      section.css('float', 'left');
      section.css('width', percent + "%");
      section.append(value);
      container.append(section);
      return section.height();
    };
    addRow = function(desc, ctrl) {
      var h1, h2;
      h1 = addItem(percentage, desc);
      h2 = addItem(100 - percentage, ctrl);
      return container.height(Math.max(h1, h2) + container.height());
    };
    pfx = function(id) {
      return prefix + "_" + id;
    };
    this.numEntry = function(id, text) {
      var e;
      e = $("<input maxlength=5 size=5 type=\"number\" id=" + (pfx(id)) + ">");
      addRow(text, e);
      return addAccessors(id, function(pfid) {
        return $('#' + pfid).val();
      }, function(pfid, val) {
        return $('#' + pfid).val(val);
      });
    };
    this.button = function(id, text, label, action) {
      var e;
      e = $("<button id=\"" + (pfx(id)) + "\">" + label + "</button>");
      addRow(text, e);
      return $("#" + (pfx(id)), container).click(action);
    };
    this.checkbox = function(id, text) {
      var e;
      e = $("<input type=\"checkbox\" id=\"" + (pfx(id)) + "\">" + text + "</input>");
      addRow("&nbsp;", e);
      return addAccessors(id, function(pfid) {
        return $('#' + pfid).prop('checked');
      }, function(pfid, val) {
        return $('#' + pfid).prop('checked', !!val);
      });
    };
    this.gridSpacer = function() {
      return addRow("&nbsp;", "&nbsp;");
    };
    this.val = function(id, value) {
      var sg;
      if (value == null) {
        value = null;
      }
      sg = value != null ? setters : getters;
      return sg[pfx(id)](pfx(id), value);
    };
  }

  return Quickform;

})();
